### ISSUE TITLE
The input message appears to the side instead of below it

### ISSUE THREAD

**Issue by JuanDominguez1** [dd3tech/bui#54]
Current
<img width="549" alt="Screenshot 2023-03-31 at 16 44 29" src="https://user-images.githubusercontent.com/127886251/229245564-e557c07b-b65f-4f84-9fd1-39219d36baed.png">

Expected
<img width="666" alt="Screenshot 2023-03-31 at 16 43 20" src="https://user-images.githubusercontent.com/127886251/229245445-8f8972a5-5948-4491-af17-93acca535e09.png">

**Comment by arielsrodriguez** [comment]
I follow it.
