### ISSUE TITLE
Add animations

### ISSUE THREAD

**Issue by Misael840** [dd3tech/bui#55]
**Is your feature request related to a problem? Please describe.**
Could be great to add optional animations to the components and also add the possibility to export those animations to use them in the project. 

**Describe the solution you'd like**
Implement a CSS animation file that contains basic animation to use in the components and project. Could be based on the Animate.css library.

**Describe alternatives you've considered**
Only implement Animate.css on the components and add a new prop to them to change the animation.

**Additional context**
https://animate.style

**Comment by tbor00** [comment]
This issue was resolved when released the `Animate` cmp
